[package]
name = "ed25519-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
web-sys = { version = "0.3", features = ["console"] }
wasm-bindgen = "0.2"
ed25519-consensus = "2.1.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
