[package]
name = "ed25519-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
ed25519-dalek = { version = "2", features = ["batch"] }
web-sys = { version = "0.3", features = ["console"] }
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
